# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_adventofcode22_wrappers", use_symbols = TRUE, package_name = "adventofcode22")

#' @docType package
#' @usage NULL
#' @useDynLib adventofcode22, .registration = TRUE
NULL

#' Calculate the solution to 1-a
#' @export
day_one_a <- function(input) .Call(wrap__day_one_a, input)

#' Calculate the solution to 1-b
#' @export
day_one_b <- function(input) .Call(wrap__day_one_b, input)

#' Calculate the solution to 2-a
#' @export
day_two_a <- function(theirs, mine) .Call(wrap__day_two_a, theirs, mine)

#' Calculate the solution to 2-a
#' @export
day_two_b <- function(theirs, mine) .Call(wrap__day_two_b, theirs, mine)

