# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_adventofcode22_wrappers", use_symbols = TRUE, package_name = "adventofcode22")

#' @docType package
#' @usage NULL
#' @useDynLib adventofcode22, .registration = TRUE
NULL

#' Calculate the solution to 1-a
#' @export
day_one_a <- function(input) .Call(wrap__day_one_a, input)

#' Calculate the solution to 1-b
#' @export
day_one_b <- function(input) .Call(wrap__day_one_b, input)

#' Calculate the solution to 2-a
#' @export
day_two_a <- function(theirs, mine) .Call(wrap__day_two_a, theirs, mine)

#' Calculate the solution to 2-b
#' @export
day_two_b <- function(theirs, mine) .Call(wrap__day_two_b, theirs, mine)

#' Calculate the solution to 2-b
#' @export
day_three_a <- function(contents) .Call(wrap__day_three_a, contents)

#' Calculate the solution to 2-b
#' @export
day_three_b <- function(contents) .Call(wrap__day_three_b, contents)

#' Calculate the solution to 4-a
#' @export
day_four_a <- function(first, second) .Call(wrap__day_four_a, first, second)

#' Calculate the solution to 4-a
#' @export
day_four_b <- function(first, second) .Call(wrap__day_four_b, first, second)

#' Calculate the solution to 5-a
#' @export
day_five_a <- function(stacks, directions) .Call(wrap__day_five_a, stacks, directions)

#' Calculate the solution to 5-b
#' @export
day_five_b <- function(stacks, directions) .Call(wrap__day_five_b, stacks, directions)

#' Calculate the solution to 6-1
#' @export
day_six_a <- function(input) .Call(wrap__day_six_a, input)

#' Calculate the solution to 6-2
#' @export
day_six_b <- function(input) .Call(wrap__day_six_b, input)

#' Calculate the solution to 7-1
#' @export
day_seven_a <- function(input) .Call(wrap__day_seven_a, input)

#' Calculate the solution to 7-2
#' @export
day_seven_b <- function(input) .Call(wrap__day_seven_b, input)

#' Calculate the solution to 10-1
#' @export
day_ten_a <- function(input, indices) .Call(wrap__day_ten_a, input, indices)

#' Calculate the solution to 10-2
#' @export
day_ten_b <- function(input) .Call(wrap__day_ten_b, input)

